pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS=credentials('dockerhub')
  }
  stages {
    stage('listing directory'){
      steps{
        sh 'ls -l'
      }
    }
    stage('build nodejs app'){
      steps{
        sh 'npm install'
        sh 'npm run build'
        sh 'ls -l'
      }
    }
    stage('build docker image'){
      steps{
        sh 'docker build -t votebmyla/reactjs-app:latest .'
        sh 'docker images'
      }
    }
  }
}