pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS=credentials('dockerhub')
  }
  stages {
    stage('listing directory'){
      steps{
        sh 'ls -l'
      }
    }
    stage('build nodejs app'){
      steps{
        sh 'npm install'
        sh 'npm run build'
        sh 'ls -l'
      }
    }
    stage('build docker image'){
      steps{
        sh 'docker build -t votebmyla/reactjs-app:latest .'
        sh 'docker images'
      }
    }
    stage('login dockerhub'){
      steps{
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('push docker image'){
      steps{
        sh 'docker push votebmyla/reactjs-app:latest'
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}